# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
# after-startup-command = [
# ]

# Start AeroSpace at login
start-at-login = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 100

# Mouse
on-focused-monitor-changed = [
    'move-mouse monitor-lazy-center',
] # Mouse lazily follows focused monitor (default in i3)
# or
# on-focus-changed = [
#     'move-mouse window-lazy-center',
# ] # Mouse lazily follows any focus (window or workspace)

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'colemak'
# colemak-dh remaps
[key-mapping.key-notation-to-key-code]
"g" = "g"
"d" = "c"
"v" = "v"
"b" = "t"
"x" = "z"
"c" = "x"
"h" = "m"
"m" = "h"

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 28]
#                 In this example, 28 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See:
#                 https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = [{ monitor.built-in = 10 }, 14]
inner.vertical = [{ monitor.built-in = 10 }, 14]
outer.left = [{ monitor.built-in = 10 }, 14]
outer.bottom = [{ monitor.built-in = 10 }, 14]
outer.top = [{ monitor.built-in = 10 }, 14]
outer.right = [{ monitor.built-in = 10 }, 14]

# [workspace-to-monitor-force-assignment]
# 1 = 'secondary'
# 2 = 'main'
# 3 = 'main'
# 4 = 'main'
# 5 = 'main'

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-period = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-left = 'focus left'
alt-down = 'focus down'
alt-up = 'focus up'
alt-right = 'focus right'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-f = 'fullscreen'
alt-shift-f = 'layout floating tiling'
alt-shift-r = 'reload-config'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-left = 'move left'
alt-shift-down = 'move down'
alt-shift-up = 'move up'
alt-shift-right = 'move right'
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-1 = 'workspace 1' # browsers
alt-2 = 'workspace 2' # dev tools
alt-3 = 'workspace 3' # organization (email, calendar, etc.)
alt-4 = 'workspace 4' # communication (chat apps, etc.)
alt-5 = 'workspace 5' # media (music, videos, etc.)
alt-6 = 'workspace 6' # gaming
alt-7 = 'workspace 7' # rest
alt-8 = 'workspace 8' # rest
alt-9 = 'workspace 9' # rest

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
alt-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
alt-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
alt-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'
alt-shift-5 = 'move-node-to-workspace 5 --focus-follows-window'
alt-shift-6 = 'move-node-to-workspace 6 --focus-follows-window'
alt-shift-7 = 'move-node-to-workspace 7 --focus-follows-window'
alt-shift-8 = 'move-node-to-workspace 8 --focus-follows-window'
alt-shift-9 = 'move-node-to-workspace 9 --focus-follows-window'

# App shortcuts
alt-t = 'exec-and-forget open -a Ghostty'
alt-b = 'exec-and-forget open -a "Brave Browser"'
alt-e = 'exec-and-forget open -a "Proton Mail"'
# Webapps, requires manual installation
alt-c = 'exec-and-forget open -a "Proton Calendar"'
alt-m = 'exec-and-forget open -a Spotify'
alt-w = 'exec-and-forget open -a "WhatsApp Web"'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

[[on-window-detected]]
if.app-name-regex-substring = 'Brave Browser|Safari|Zen|Google Chrome|Chromium|Vivaldi|Firefox'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-name-regex-substring = 'Ghostty|Kitty|Alacritty'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-name-regex-substring = 'Mail|Calendar'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-name-regex-substring = 'WhatsApp|Signal'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-name-regex-substring = 'Spotify|Apple Music'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-name-regex-substring = 'Steam Helper|Heroic'
run = ['layout tiling', 'move-node-to-workspace 6']
