# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
    'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=3.0',
]

# Start AeroSpace at login
start-at-login = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 50


# Mouse
on-focused-monitor-changed = [
    'move-mouse monitor-lazy-center',
] # Mouse lazily follows focused monitor (default in i3)
# or
on-focus-changed = [
    'move-mouse window-lazy-center',
] # Mouse lazily follows any focus (window or workspace)

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'colemak'
# colemak-dh remaps
[key-mapping.key-notation-to-key-code]
"g" = "g"
"d" = "c"
"v" = "v"
"b" = "t"
"x" = "z"
"c" = "x"
"h" = "m"
"m" = "h"

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 28]
#                 In this example, 28 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See:
#                 https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = [{ monitor.built-in = 3 }, 10]
inner.vertical = [{ monitor.built-in = 3 }, 10]
outer.left = [{ monitor.built-in = 3 }, 10]
outer.bottom = [{ monitor.built-in = 3 }, 10]
outer.top = [{ monitor.built-in = 3 }, 10]
outer.right = [{ monitor.built-in = 3 }, 10]


[workspace-to-monitor-force-assignment]
1 = 'built-in'
2-5 = 'main'


# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-period = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-left = 'focus left'
alt-down = 'focus down'
alt-up = 'focus up'
alt-right = 'focus right'

alt-f = 'fullscreen'
alt-shift-f = 'layout floating tiling'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-left = 'move left'
alt-shift-down = 'move down'
alt-shift-up = 'move up'
alt-shift-right = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-1 = 'workspace 1' # browsers
alt-2 = 'workspace 2' # dev (terminal)
alt-3 = 'workspace 3' # media
alt-4 = 'workspace 4' # communication
alt-5 = 'workspace 5' # rest

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
alt-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
alt-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
alt-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'
alt-shift-5 = 'move-node-to-workspace 5 --focus-follows-window'

alt-t = 'exec-and-forget open -a Ghostty'
alt-b = 'exec-and-forget open -a "Brave Browser"'
alt-n = 'exec-and-forget open -a Notes'
alt-e = 'exec-and-forget open -a Mail'
alt-m = 'exec-and-forget open -a Spotify'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

[[on-window-detected]]
if.app-name-regex-substring = 'Brave Browser|Safari|Zen'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-name-regex-substring = 'Ghostty|Kitty|Alacritty'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-name-regex-substring = 'Spotify'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-name-regex-substring = 'Mail'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-name-regex-substring = 'Steam Helper'
run = ['layout tiling', 'move-node-to-workspace 5']
