[general]
import = [
    # "./themes/catppuccin-mocha.toml",
    "./themes/tokyo-night-moon.toml",
    # "./themes/dracula.toml",
]

[window]
decorations = "buttonless"
dynamic_padding = true
# opacity = 0.9
# blur = true

[font]
normal.family = "JetBrainsMonoNL Nerd Font"
size = 15

[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = true

[colors]
# primary.background = "#111111"
