[general]
import = ["./theme.toml"]

[window]
decorations = "buttonless"
padding.x = 2
dynamic_padding = true
# opacity = 0.9
# blur = true
startup_mode = "Fullscreen"

[font]
normal.family = "JetBrainsMonoNL Nerd Font"
size = 15

[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = true
