# Oxocarbon Color Scheme for Alacritty in TOML format

# Primary colors
[colors.primary]
background = "#161616"
foreground = "#ffffff"

# Search colors
[colors.search.matches]
foreground = "CellBackground"
background = "#ee5396"

# Normal colors
[colors.normal]
black = "#262626"
magenta = "#ff7eb6"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
red = "#ee5396"
cyan = "#3ddbd9"
white = "#dde1e6"

# Bright colors
[colors.bright]
black = "#393939"
magenta = "#ff7eb6"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
red = "#ee5396"
cyan = "#3ddbd9"
white = "#ffffff"
