theme = "tokyonight_moon"

[editor]
line-number = "relative"
end-of-line-diagnostics = "hint"
color-modes = true

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
